[package]
name = "live"
version = "0.1.0"
authors = ["Nuria <nuria@codegram.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.50"
rand = "0.6"
colored = "1.8"
regex = "1"