version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
jobs:
  build:
    executor: rust/default
    steps:
      - checkout
      - rust/update_toolchain
      - rust/build:
          release: true
workflows:
  main:
    jobs:
      - build