version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
jobs:
  build:
    executor: rust/default
    steps:
      - checkout
      - rust/update_toolchain
      - rust/build:
          release: true
      - run: curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
      - run: unzip butler.zip
      - run: chmod +x butler
      - run: ./butler push /root/project/target/release/live nuria/live-rust:linux-universal
workflows:
  main:
    jobs:
      - build